### PR TITLE
ESX Support

### PR DESCRIPTION
**Pull request by lenzh**
Made it job related and not ped related ;) and its working with ESX

**Installation**
Place in your resources folder, just like [any other ESX resource] in your [ESX]

in server.cfg
`````
start advanced911
`````

### CODE REVIEW

**Comment by lze3** [comment]
Hola? English? You read English? You no read the "Standalone"??

**Comment by lenzh** [comment]
Hola i talked with FAXES so no worries :)

**Comment by lze3** [comment]
Perhaps on a separate repository/branch but not on the same repository overwriting all of the standalone features. Who wants to use ES-Gay?

**Comment by lenzh** [comment]
Like i said i talked with FAXES

**Comment by FAXES** [comment]
I would've said to ensure its in its own folder so there' still the standalone option most likely.

**Pull request closed without merging**
